artifacts_root : artifacts

# Data Ingestion

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_URL : https://github.com/codedestructed007/Datasets/raw/main/winequality-white.zip
  local_data_file  : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion

# Data validation

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  unzip_data_dir: artifacts/data_ingestion/winequality-white.csv